name: Build

on: push


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare enviroment
        run: sudo apt update && sudo apt install gcc-arm-none-eabi && sudo apt install gcovr

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build app
        run: ./tools/scripts/build.sh Release

      - name: Run tests and coverage
        run: ./tools/scripts/genCoverage.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/Release/app.elf
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage