name: Build
on: [push, pull_request] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update repositories
        run: apt update
      
      - name: Install gcc
        run: apt install gcc-arm-none-eabi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build app
        run: ./tols/script/build.sh Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/Release/app.elf
