name: Release

on:
  push:
    tags: '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare environment
        run: sudo apt update && sudo apt install gcc-arm-none-eabi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build app
        run: ./tools/scripts/build.sh Release

      - name: Run tests and coverage
        run: ./tools/scripts/genCoverage.sh

      - name: Get the latest release
        id: get_latest_release
        uses: actions/github-script@v6
        with:
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            if (releases.length === 0) {
              throw new Error('No releases found');
            }
            return releases[0].upload_url;
          result-encoding: string

      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_latest_release.outputs.result }}
          asset_path: build/Release/app.elf
          asset_name: app.elf
          asset_content_type: application/elf

      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_latest_release.outputs.result }}
          asset_path: coverage
          asset_name: coverage
          asset_content_type: application/folder